### ISSUE TITLE
How to run diffpure on one single image?

### ISSUE THREAD

**Issue by universewill** [NVlabs/DiffPure#11]
How to run diffpure on one single image?

**Comment by weilinie** [comment]
If it's about running DiffPure on a single image randomly sampled from CIFAR-10/ImageNet, you can simply set `num_sub=1` and `adv_batch_size=1`, and run it on a single GPU.

**Comment by pearlmary** [comment]
Hi,

If I have a single adversarial image, how should I use the code to perform adversarial cleaning on the single image and generate a clean image?

Many Thanks in Advance

**Comment by zhongguadepi** [comment]
> 你好，
> 
> 如果我有单个对抗性图像，我应该如何使用代码对单个图像执行对抗性清理并生成干净的图像？
> 
> 提前谢谢了
Hello. Regarding the question you raised on how to use code to perform adversarial purification on a single image and generate a clean image, has it been resolved?
