### ISSUE TITLE
Can authors release a more complete version containing basic descriptions for python files and functions and so on?

### ISSUE THREAD

**Issue by liguopeng0923** [NVlabs/DiffPure#13]
For example, what is "counter"? When to stop?

**Comment by weilinie** [comment]
Thanks for your request. We use `counter` to record the the sampling time every 5 NFEs (note we hardcoded print freq to 5, and you may want to change the freq). The evaluation script for each batch will automatically stop when the threat model traverses all the predefined iterations and restarts or successfully attack the whole batch samples. Let me know you have other questions about the files and functions.
