### ISSUE TITLE
Checkpoint of Classifier WideResNet-28-10

### ISSUE THREAD

**Issue by ZhangMingKun1** [NVlabs/DiffPure#14]
Hi, can you provide the checkpoint of WideResNet-28-10 that used for evaluation in your experiment?

**Comment by huanranchen** [comment]
Hi~ Have you got checkpoint of WideResNet-28-10 (Zhang et al., 2020)? I also need it~~

**Comment by weilinie** [comment]
The checkpoint of WideResNet-28-10 will be automatically downloaded; see [this line](https://github.com/NVlabs/DiffPure/blob/39f37fa13e56cd4e4771a168386e5b6619204fee/utils.py#L176) for more information.
