### ISSUE TITLE
Can I use ImageNet dataset directly without converting them to LMDB format?

### ISSUE THREAD

**Issue by mijinkoo** [NVlabs/DiffPure#21]
Hi, thanks for sharing your code!

Is there a way to use ImageNet datasets directly without converting them to LMDB format? If you have the code, could you provide it?

**Comment by mijinkoo** [comment]
I solved it
Thank you!

**Comment by keenlooks** [comment]
Could you describe how you solved this issue please? I tried to use the current code's LMDB format conversion but the base classifier gets 0% accuracy on it.
