### ISSUE TITLE
ValueError: attacks_to_run will be overridden unless you use version='custom'

### ISSUE THREAD

**Issue by zhang-f** [NVlabs/DiffPure#23]
I just run:
`python3 eval_sde_adv.py --exp ./exp_results --config cifar10.yml \
          -i cifar10-robust_adv-$t-eps$adv_eps-64x1-bm0-t0-end1e-5-cont-eot20 \
          --t 100 \
          --adv_eps 0.031373 \
          --adv_batch_size 128 \
          --num_sub 64 \
          --domain cifar10 \
          --classifier_name cifar10-wideresnet-28-10 \
          --seed 121 \
          --data_seed 6 \
          --diffusion_type  ode\
          --score_type score_sde \
          --attack_version rand \
          --eot_iter 20 \
`
And get the error:
`raise ValueError("attacks_to_run will be overridden unless you use version='custom'")
ValueError: attacks_to_run will be overridden unless you use version='custom'
`
I also changed the 'rand' to 'standard', just got the same error.

**Comment by zhihao-2022** [comment]
The same question I have met.

**Comment by zhihao-2022** [comment]
can you give me your WeChat number? Maybe we can have some communication.

**Comment by zhang-f** [comment]
> The same question I have met.

I just delete the line 28-29 in auto attack, https://github.com/fra31/auto-attack/blob/a39220048b3c9f2cca9a4d3a54604793c68eca7e/autoattack/autoattack.py#L28
