### ISSUE TITLE
ImportError: cannot import name 'SqueezeExcitation' from 'torchvision.ops.misc'

### ISSUE THREAD

**Issue by roy-ch** [NVlabs/DiffPure#25]
when I run: sh run_cifar_rand_L2.sh 121 5, it reports ImportError: cannot import name 'SqueezeExcitation' from 'torchvision.ops.misc'

**Comment by weilinie** [comment]
It may be due to the torchvision version. Can you install `torchvision==0.8.2` as specified [here](https://github.com/NVlabs/DiffPure/blob/master/diffpure.Dockerfile)?

**Comment by roy-ch** [comment]
I have already solved this problem. The error was caused by the incompatibility due to the version update of RobustBench. The default download version of RobustBench is v1.1.1-test, which is only compatible with torchvision 0.16.

All you need to do is change the last line of [diffpure.Dockerfile](https://git.woa.com/cusmochen/diffpure/blob/master/diffpure.Dockerfile) from:

`git+https://github.com/RobustBench/robustbench.git`

to:

`git+https://github.com/RobustBench/robustbench.git@v1.0`
