### ISSUE TITLE
Customized for different attacks

### ISSUE THREAD

**Issue by JCL823** [NVlabs/DiffPure#3]
Greetings,

I really enjoy reading your paper! Thank you for sharing the codes! 

I'm wondering if it's possible to add some instructions about how to implement DiffPure on customized attacks (white-box/ black-box; or targeted/ untargeted)?

**Comment by weilinie** [comment]
Thanks for your interest in our work. To evaluate DiffPure on customized attacks, you can simply add a customized attack evaluation function in the `eval_sde_adv.py` file (inside the function [`robustness_eval`](https://github.com/NVlabs/DiffPure/blob/master/eval_sde_adv.py#L232)):
```python
# eval classifier and sde_adv against attacks
if args.attack_version in ['standard', 'rand', 'custom']:
    eval_autoattack(args, config, model, x_val, y_val, adv_batch_size, log_dir)
elif args.attack_version == 'stadv':
    eval_stadv(args, config, model, x_val, y_val, adv_batch_size, log_dir)
else:
    raise NotImplementedError(f'unknown attack_version: {args.attack_version}')
```
In most cases, you don't need to change the DiffPure implementation. See how we implemented the attack evaluations ([eval_autoattack](https://github.com/NVlabs/DiffPure/blob/master/eval_sde_adv.py#L94) and [eval_sde_adv](https://github.com/NVlabs/DiffPure/blob/master/eval_sde_adv.py#L156)) for AutoAttack and StAdv, respectively.

Please let us know if you have further questions or run into any issue.
