### ISSUE TITLE
run_cifar_rand_inf.sh robust accuracy 0%

### ISSUE THREAD

**Issue by nfsrules** [NVlabs/DiffPure#5]
Hi, thanks for the great contribution. I'm trying to reproduce the results of the paper (Table6). 

I've the tried autoattack rand inf, using the following script:

`` bash run_cifar_rand_inf.sh 0 0 ``

On the experiment logs, the robust accuracy always returns 0%.

Am I doing something wrong?

Thanks!

**Comment by weilinie** [comment]
Hi @nfsrules, may I ask which experiment logs are you looking into? Can you share the log information here?

**Comment by nfsrules** [comment]
Hi @weilinie! It's VP-SDE wide resnet 28-10 on Table6.

Yes, sure, here are the logs:
[log_sde_adv.txt](https://github.com/NVlabs/DiffPure/files/9329072/log_sde_adv.txt)
[log_resnet.txt](https://github.com/NVlabs/DiffPure/files/9329074/log_resnet.txt)
![logs](https://user-images.githubusercontent.com/23075615/184420531-dcc25efe-6201-4470-be00-09d2a518c9ac.PNG)

**Comment by weilinie** [comment]
In the log.txt that you shared, it seems like you use `t=10` instead of `t=100` as we used in Table 6. This might be the reason why we see a higher initial acc but a much lower robust acc.

**Comment by nfsrules** [comment]
Oh, that clarifies a lot. Thank you.
