### ISSUE TITLE
Where to get the pretrained models for cifar 10

### ISSUE THREAD

**Issue by wzic** [NVlabs/DiffPure#6]
Hi! I notice that 'TBD' is annotated for the pretrained models for cifar 10 experiments in README. May I know if there is an official link to get these pretrained models?

**Comment by hanqingguo** [comment]
I have the same question, do you find the correct link yet?

**Comment by wzic** [comment]
Not yet. There seems many different versions of pretrained resnet50 models on the internet. Not sure which to use.

**Comment by hanqingguo** [comment]
Hi I trained one resnet50 based on his defined model. And change the idx_start=0 in the utils, then the model can be loaded successfully. You can download it from here: https://drive.google.com/file/d/1gHNc4Vcfs5FwIex8e_80_bfNc_46EAGg/view?usp=sharing

**Comment by weilinie** [comment]
The cifar10 pertained models have been released.
