### ISSUE TITLE
Question about diffusion times.

### ISSUE THREAD

**Issue by glin2022** [NVlabs/DiffPure#7]
Hi! I have some questions about variable 'diffusion times'.
1. This variable name confuses me, does it refer to the round of the attack iteration? Or something else?
2. My program goes to `x_adv_sde = adversary_sde.run_standard_evaluation(x_val, y_val, bs=adv_batch_size)` with diffusion times: 1245, which is still rising. What I want to know is when will it be finished?

**Comment by weilinie** [comment]
The total number of diffusion times ~= number of attack iterations * number of diffusion steps (e.g., t* x 1000).

**Comment by glin2022** [comment]
Thank you very much for your reply! May I ask some more question?
In the eval_sde_adv.py: 
1. What are the corresponding variable names for 'number of attack iterations' and 'number of diffusion steps'? Can I modify them?
2. What is the relationship between Diffusion timestep t* (in paper) and Sampling noise scale t (in code)?

**Comment by weilinie** [comment]
1. The number of attack iterations depends on the attack you selected. For example, if you use the square attack, the default setting with `adversary_resnet.square.n_queries = 5000` means we will do 5000 attack iterations. Also, the `t` variable (i.e., the sampling noise scale) corresponds to the number of diffusion steps.
2. t = t* x 1000
3. There is no training in the DiffPure defense given the pre-trained diffusion models and classifiers. The `train_util.py` in the `guided_diffusion` folder is derived from the guided diffusion repo, and it is not directly related to any training in our work.

**Comment by glin2022** [comment]
I see. Thank you very much!

**Comment by glin2022** [comment]
Great answer!
