### ISSUE TITLE
How to build the environment without Docker? Could you please provide a requirement.txt?

### ISSUE THREAD

**Issue by LiQiiiii** [NVlabs/DiffPure#8]

**Comment by thuwzy** [comment]
Have you built the environment without Docker successfully?

**Comment by LiQiiiii** [comment]
> Have you built the environment without Docker successfully?

Yes, just install those packages in the Dockerfile one by one.

**Comment by thuwzy** [comment]
> > Have you built the environment without Docker successfully?
> 
> Yes, just install those packages in the Dockerfile one by one.

Thank you!
